name: Deploy WebApplication2 to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Build and Publish WebApplication2
        run: |
          dotnet restore
          dotnet publish WebApplication2/WebApplication2.csproj -c Release -o "${{ github.workspace }}/published"

      - name: Prepare Directory Structure
        run: |
          # Create the correct virtual application structure
          $deployPath = "${{ github.workspace }}/deploy/WebApplication2"
          New-Item -ItemType Directory -Path $deployPath -Force
          
          # Move all published files to the virtual application directory
          Get-ChildItem -Path "${{ github.workspace }}/published" | Copy-Item -Destination $deployPath -Recurse -Force

      - name: Create ZIP Package
        run: Compress-Archive -Path "${{ github.workspace }}/deploy/*" -DestinationPath "${{ github.workspace }}/WebApplication2.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApplication2
          path: ${{ github.workspace }}/WebApplication2.zip

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build
    environment:
      name: Production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebApplication2
          path: ${{ github.workspace }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Git-webapp'
          virtual-application: 'WebApplication2'
          package: ${{ github.workspace }}/WebApplication2.zip
