name: Deploy WebApplication2 to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'WebApplication2/**'
      - '.github/workflows/deploy-webapp.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Publish WebApplication2
        run: dotnet publish WebApplication2/WebApplication2.csproj -c Release -o ${{ github.workspace }}/deploy/WebApplication2

      # Create the correct directory structure without extra wwwroot
      - name: Create Directory Structure
        run: |
          mkdir -p ${{ github.workspace }}/deploy/temp/WebApplication2
          Move-Item -Path ${{ github.workspace }}/deploy/WebApplication2/* -Destination ${{ github.workspace }}/deploy/temp/WebApplication2/

      # Add deployment script
      - name: Create Deploy Script
        shell: cmd
        run: |
          echo @echo off > ${{ github.workspace }}/deploy/temp/deploy.cmd
          echo if not exist "%%DEPLOYMENT_TARGET%%\WebApplication2" mkdir "%%DEPLOYMENT_TARGET%%\WebApplication2" >> ${{ github.workspace }}/deploy/temp/deploy.cmd
          echo xcopy /Y /E /I "%%DEPLOYMENT_SOURCE%%\WebApplication2\*" "%%DEPLOYMENT_TARGET%%\WebApplication2\" >> ${{ github.workspace }}/deploy/temp/deploy.cmd

      - name: Create ZIP Package
        run: Compress-Archive -Path "${{ github.workspace }}/deploy/temp/*" -DestinationPath "${{ github.workspace }}/WebApplication2.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApplication2
          path: ${{ github.workspace }}/WebApplication2.zip

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebApplication2
          path: ${{ github.workspace }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy WebApplication2 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Git-webapp'
          package: ${{ github.workspace }}/WebApplication2.zip
          #slot-name: 'production'
