name: Deploy WebApplication2 to Azure Web App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Publish WebApplication2
        run: dotnet publish WebApplication2/WebApplication2.csproj -c Release -o ${{ github.workspace }}/deploy/temp/site/wwwroot/WebApplication2

      - name: Create ZIP Package
        run: Compress-Archive -Path "${{ github.workspace }}/deploy/temp/*" -DestinationPath "${{ github.workspace }}/WebApplication2.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApplication2
          path: ${{ github.workspace }}/WebApplication2.zip

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebApplication2
          path: ${{ github.workspace }}
      
      - name: Extract ZIP Package
        run: Expand-Archive -Path "${{ github.workspace }}/WebApplication2.zip" -DestinationPath "${{ github.workspace }}/deploy"
      
      # Create .deployment file
      - name: Create .deployment file
        run: |
          Set-Content -Path "${{ github.workspace }}/deploy/.deployment" -Value @"
          [config]
          SCM_TOUCH_WEBCONFIG_AFTER_DEPLOYMENT=0
          command=deploy.cmd
          "@
      
      # Create deployment script
      - name: Create Deploy Script
        shell: cmd
        run: |
          echo @echo off > "${{ github.workspace }}/deploy/deploy.cmd"
          echo echo Copying files to WebApplication2 directory... >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo if not exist "%%DEPLOYMENT_TARGET%%\WebApplication2" mkdir "%%DEPLOYMENT_TARGET%%\WebApplication2" >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo xcopy /Y /E /I "%%DEPLOYMENT_SOURCE%%\site\wwwroot\WebApplication2" "%%DEPLOYMENT_TARGET%%\WebApplication2\" >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo if %%ERRORLEVEL%% NEQ 0 goto error >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo echo Deployment Successful. >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo goto end >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo :error >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo echo An error has occurred during web site deployment. >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo exit /b 1 >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo :end >> "${{ github.workspace }}/deploy/deploy.cmd"
          echo echo Finished successfully. >> "${{ github.workspace }}/deploy/deploy.cmd"
      
      # Create new ZIP with deployment files
      - name: Create Updated ZIP Package
        run: |
          Remove-Item "${{ github.workspace }}/WebApplication2.zip"
          Compress-Archive -Path "${{ github.workspace }}/deploy/*" -DestinationPath "${{ github.workspace }}/WebApplication2.zip"
  
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Stop Azure Web App
        run: az webapp stop --name Git-webapp --resource-group Git-grp
        continue-on-error: true
        
      - name: Deploy WebApplication2 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Git-webapp'
          package: ${{ github.workspace }}/WebApplication2.zip
          
      - name: Start Azure Web App
        run: az webapp start --name Git-webapp --resource-group Git-grp
